ALTER TABLE [dbo].[Student]
    ADD CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED ([No] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

