//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCallSystem.RollCallServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RollCallServiceReference.IRollCallService")]
    public interface IRollCallService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/sendEmail", ReplyAction="http://tempuri.org/IRollCallService/sendEmailResponse")]
        bool sendEmail(string sendTo, string subject, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/checkUser", ReplyAction="http://tempuri.org/IRollCallService/checkUserResponse")]
        bool checkUser(string userName, string password, int permission);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/addClass", ReplyAction="http://tempuri.org/IRollCallService/addClassResponse")]
        int addClass(string className, string admin, string password, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/addStudent", ReplyAction="http://tempuri.org/IRollCallService/addStudentResponse")]
        void addStudent(int no, string name, int classID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/addCourse", ReplyAction="http://tempuri.org/IRollCallService/addCourseResponse")]
        void addCourse(System.Guid courseID, string courseName, int classID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/addRecordIndex", ReplyAction="http://tempuri.org/IRollCallService/addRecordIndexResponse")]
        void addRecordIndex(System.Guid indexID, System.DateTime date, System.Guid courseID, int classID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/addRecord", ReplyAction="http://tempuri.org/IRollCallService/addRecordResponse")]
        void addRecord(System.Guid recordID, int studentNo, string record, string remark, System.Guid recordIndex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/isClassExist", ReplyAction="http://tempuri.org/IRollCallService/isClassExistResponse")]
        bool isClassExist(int classID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/updateClassInfo", ReplyAction="http://tempuri.org/IRollCallService/updateClassInfoResponse")]
        void updateClassInfo(int classID, string admin, string password, string phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/updateStudent", ReplyAction="http://tempuri.org/IRollCallService/updateStudentResponse")]
        void updateStudent(int no, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/updateCourse", ReplyAction="http://tempuri.org/IRollCallService/updateCourseResponse")]
        void updateCourse(System.Guid courseID, string courseName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/updateRecord", ReplyAction="http://tempuri.org/IRollCallService/updateRecordResponse")]
        void updateRecord(System.Guid recordID, string record, string remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/deleteStudent", ReplyAction="http://tempuri.org/IRollCallService/deleteStudentResponse")]
        void deleteStudent(int no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/deleteCourse", ReplyAction="http://tempuri.org/IRollCallService/deleteCourseResponse")]
        void deleteCourse(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollCallService/deleteRecordIndex", ReplyAction="http://tempuri.org/IRollCallService/deleteRecordIndexResponse")]
        void deleteRecordIndex(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRollCallServiceChannel : RollCallSystem.RollCallServiceReference.IRollCallService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RollCallServiceClient : System.ServiceModel.ClientBase<RollCallSystem.RollCallServiceReference.IRollCallService>, RollCallSystem.RollCallServiceReference.IRollCallService {
        
        public RollCallServiceClient() {
        }
        
        public RollCallServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RollCallServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RollCallServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RollCallServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool sendEmail(string sendTo, string subject, string content) {
            return base.Channel.sendEmail(sendTo, subject, content);
        }
        
        public bool checkUser(string userName, string password, int permission) {
            return base.Channel.checkUser(userName, password, permission);
        }
        
        public int addClass(string className, string admin, string password, string phone) {
            return base.Channel.addClass(className, admin, password, phone);
        }
        
        public void addStudent(int no, string name, int classID) {
            base.Channel.addStudent(no, name, classID);
        }
        
        public void addCourse(System.Guid courseID, string courseName, int classID) {
            base.Channel.addCourse(courseID, courseName, classID);
        }
        
        public void addRecordIndex(System.Guid indexID, System.DateTime date, System.Guid courseID, int classID) {
            base.Channel.addRecordIndex(indexID, date, courseID, classID);
        }
        
        public void addRecord(System.Guid recordID, int studentNo, string record, string remark, System.Guid recordIndex) {
            base.Channel.addRecord(recordID, studentNo, record, remark, recordIndex);
        }
        
        public bool isClassExist(int classID) {
            return base.Channel.isClassExist(classID);
        }
        
        public void updateClassInfo(int classID, string admin, string password, string phone) {
            base.Channel.updateClassInfo(classID, admin, password, phone);
        }
        
        public void updateStudent(int no, string name) {
            base.Channel.updateStudent(no, name);
        }
        
        public void updateCourse(System.Guid courseID, string courseName) {
            base.Channel.updateCourse(courseID, courseName);
        }
        
        public void updateRecord(System.Guid recordID, string record, string remark) {
            base.Channel.updateRecord(recordID, record, remark);
        }
        
        public void deleteStudent(int no) {
            base.Channel.deleteStudent(no);
        }
        
        public void deleteCourse(System.Guid id) {
            base.Channel.deleteCourse(id);
        }
        
        public void deleteRecordIndex(System.Guid id) {
            base.Channel.deleteRecordIndex(id);
        }
    }
}
